[package]
version = "0.1.0"
name = "sp1-sha-script"
edition = "2021"

[dependencies]
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git" }
bincode = "1.3"
serde = "1"
chrono = "0.4"
[build-dependencies]
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git" }